sudo: required
language: rust
rust:
    - nightly-2019-05-28
dist: bionic
notifications:
  email: false
matrix:
  include:
    - rust: nightly-2019-05-28
env:
    - SYSTEM_CARGO=1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-utils build-essential pciutils linux-headers-`uname -r` python python3  libssl-dev
  - sudo apt-get install -qq libgnutls30 libgnutls-dev libcurl4-gnutls-dev cmake bash libpcap-dev libnuma-dev
services:
  - docker
before_script:
  - sudo sysctl -w vm.nr_hugepages=256
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge
script:
  - ./build.sh
before_deploy:
  - cargo doc --all --document-private-items --bins
  - echo '<meta http-equiv=refresh content=0;url=e2d2/index.html>' > target/doc/index.html
  - mkdir public
  - cp -r target/doc public/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public
  on:
    branch: dev
