[workspace]
members=["framework",
        "test/framework-test",
        "test/delay-test",
        "test/macswap",
        "test/shutdown-test",
        "test/chain-test",
        "test/lpm",
        "test/lpm-embedded",
        "test/nat",
        "test/maglev",
        "test/packet_generation",
        "test/packet-test",
        "test/tcp-check",
        "test/tcp_payload",
        "test/sctp-test",
        "test/config-test",
        "test/reset-parse",
        "test/tcp-reconstruction",
        "test/acl-fw",
        "test/embedded-scheduler-test",
        "test/embedded-scheduler-dependency-test"]
[profile.release]
opt-level = 3
lto = true
rpath = true
debug = true
debug-assertions = false

