[workspace]
members=["framework",
        "test/framework-test",
        "test/delay-test",
        "test/macswap",
        "test/shutdown-test",
        "test/lpm-embedded",
        "test/nat",
        "test/packet_generation",
        "test/packet_test",
        "test/tcp_payload",
        "test/sctp-test",
        "test/embedded-scheduler-dependency-test",
        "test/embedded-scheduler-test",
        "test/config-test",
        "test/reset-parse",
        # ZCSI examples
        "test/tcp-reconstruction",
        "test/lpm",
        "test/lpm-test",
        "test/maglev",
        "test/tcp-check",
        "test/chain-test",
        "test/acl-fw",
        # PVN examples
	"test/tls-validator-transform",
        "test/tls-validator-filter",
        "test/tls-validator-groupby",
        "test/wd-rdr-proxy",
        "test/rdr-transform",
        "test/rdr-filter",
        "test/rdr-groupby",
        "test/transcoder-transform",
        "test/transcoder-filter",
        "test/transcoder-groupby",
        "test/rdr-proxy",
        "test/p2p",
        "test/p2p-transform",
        "test/p2p-filter",
        "test/p2p-groupby",
        "test/pktgen-test",
        "test/adv-acl"]

[profile.release]
opt-level = 3
lto = true
rpath = true
debug = true    # for profiling
debug-assertions = false

