[package]
name = "rdr-groupby"
version = "0.2.0"
authors = ['Shuwen "Jethro" Sun <jethrosun@ccs.neu.edu>']
edition = "2018"

[dependencies]
e2d2 = { path = "../../framework", features = ["performance"] }
time = "0.1.42"
getopts = "*"
fnv = "*"
twox-hash = "*"
log = "0.4"
failure = "*"
tiny_http = "0.6"
rshttp = { git = "https://github.com/jethrosun/http", branch = "pvn" }
headless_chrome = { git = "https://github.com/jethrosun/rust-headless-chrome", branch = "pvn-0.9" }
rustc-serialize = "*"
serde_json = "*"

[features]
default = []
print = []
