[package]
name = "e2d2"
version = "0.2.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]
build = "build.rs"

[lib]
doctest = false

[dependencies]
libc = ">= 0.2.4"
time = ">=0.1.0"
getopts = "*"
byteorder = "*"
fnv = "*"
twox-hash = "*"
regex = "*"
lazy_static = "*"
net2 = "*"
# NIX restricts us to just unix for now, we can fix this if someone cares at a later point.
nix = "*"
# Figure out if we want this permanently or just for now.
rust-sctp = { git="https://github.com/netsys/rust-sctp", optional = true}
toml = "*"
# Hack for SHM
uuid= { version = "*", features=["v4"] }
error-chain = "*"
clippy = { version = "*", optional = true }

[features]
default = []
performance = []
dev = ["clippy"]
packet_offset = []
sctp = ["rust-sctp"]

[build-dependencies]
# Use Bindgen to generate DPDK structures.
# NOTE(jethros): bumped bindgen version.
#bindgen = "0.50.0"
bindgen = "0.31.0"
